version: '3.3'

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - 5435:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 8080:80

